spring:
  datasource:
    url: jdbc:mysql://192.168.72.30:3306/test
    username: kty
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true